server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    #?????
    database: 6
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
  data:
    elasticsearch: 192.168.0.104

es:
  host: localhost
  port: 9300
  clusterName: myEs
  pool: 5