server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://101.143.102.16:3306/yisearch?useSSL=false
    username: root
    password: Wzr@3379779
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    #?????
    database: 6
    host: 101.143.102.16
    port: 6379
    password:
    timeout: 5000

es:
  host: localhost
  port: 9300
  clusterName: myEs
  pool: 5