// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EditDistList.proto

package pythonService;

public final class EditDistList {
  private EditDistList() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EditDistRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pythonService.EditDistRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string query = 1;</code>
     */
    java.util.List<java.lang.String>
        getQueryList();
    /**
     * <code>repeated string query = 1;</code>
     */
    int getQueryCount();
    /**
     * <code>repeated string query = 1;</code>
     */
    java.lang.String getQuery(int index);
    /**
     * <code>repeated string query = 1;</code>
     */
    com.google.protobuf.ByteString
        getQueryBytes(int index);

    /**
     * <code>string target = 2;</code>
     */
    java.lang.String getTarget();
    /**
     * <code>string target = 2;</code>
     */
    com.google.protobuf.ByteString
        getTargetBytes();
  }
  /**
   * Protobuf type {@code pythonService.EditDistRequest}
   */
  public  static final class EditDistRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pythonService.EditDistRequest)
      EditDistRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EditDistRequest.newBuilder() to construct.
    private EditDistRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EditDistRequest() {
      query_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      target_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EditDistRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                query_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              query_.add(s);
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              target_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          query_ = query_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pythonService.EditDistList.internal_static_pythonService_EditDistRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pythonService.EditDistList.internal_static_pythonService_EditDistRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pythonService.EditDistList.EditDistRequest.class, pythonService.EditDistList.EditDistRequest.Builder.class);
    }

    private int bitField0_;
    public static final int QUERY_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList query_;
    /**
     * <code>repeated string query = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getQueryList() {
      return query_;
    }
    /**
     * <code>repeated string query = 1;</code>
     */
    public int getQueryCount() {
      return query_.size();
    }
    /**
     * <code>repeated string query = 1;</code>
     */
    public java.lang.String getQuery(int index) {
      return query_.get(index);
    }
    /**
     * <code>repeated string query = 1;</code>
     */
    public com.google.protobuf.ByteString
        getQueryBytes(int index) {
      return query_.getByteString(index);
    }

    public static final int TARGET_FIELD_NUMBER = 2;
    private volatile java.lang.Object target_;
    /**
     * <code>string target = 2;</code>
     */
    public java.lang.String getTarget() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        target_ = s;
        return s;
      }
    }
    /**
     * <code>string target = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTargetBytes() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        target_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < query_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, query_.getRaw(i));
      }
      if (!getTargetBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, target_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < query_.size(); i++) {
          dataSize += computeStringSizeNoTag(query_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getQueryList().size();
      }
      if (!getTargetBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, target_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pythonService.EditDistList.EditDistRequest)) {
        return super.equals(obj);
      }
      pythonService.EditDistList.EditDistRequest other = (pythonService.EditDistList.EditDistRequest) obj;

      boolean result = true;
      result = result && getQueryList()
          .equals(other.getQueryList());
      result = result && getTarget()
          .equals(other.getTarget());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getQueryCount() > 0) {
        hash = (37 * hash) + QUERY_FIELD_NUMBER;
        hash = (53 * hash) + getQueryList().hashCode();
      }
      hash = (37 * hash) + TARGET_FIELD_NUMBER;
      hash = (53 * hash) + getTarget().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pythonService.EditDistList.EditDistRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pythonService.EditDistList.EditDistRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pythonService.EditDistList.EditDistRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pythonService.EditDistList.EditDistRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pythonService.EditDistList.EditDistRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pythonService.EditDistList.EditDistRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pythonService.EditDistList.EditDistRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pythonService.EditDistList.EditDistRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pythonService.EditDistList.EditDistRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pythonService.EditDistList.EditDistRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pythonService.EditDistList.EditDistRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pythonService.EditDistList.EditDistRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pythonService.EditDistList.EditDistRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pythonService.EditDistRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pythonService.EditDistRequest)
        pythonService.EditDistList.EditDistRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pythonService.EditDistList.internal_static_pythonService_EditDistRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pythonService.EditDistList.internal_static_pythonService_EditDistRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pythonService.EditDistList.EditDistRequest.class, pythonService.EditDistList.EditDistRequest.Builder.class);
      }

      // Construct using pythonService.EditDistList.EditDistRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        query_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        target_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pythonService.EditDistList.internal_static_pythonService_EditDistRequest_descriptor;
      }

      public pythonService.EditDistList.EditDistRequest getDefaultInstanceForType() {
        return pythonService.EditDistList.EditDistRequest.getDefaultInstance();
      }

      public pythonService.EditDistList.EditDistRequest build() {
        pythonService.EditDistList.EditDistRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pythonService.EditDistList.EditDistRequest buildPartial() {
        pythonService.EditDistList.EditDistRequest result = new pythonService.EditDistList.EditDistRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          query_ = query_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.query_ = query_;
        result.target_ = target_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pythonService.EditDistList.EditDistRequest) {
          return mergeFrom((pythonService.EditDistList.EditDistRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pythonService.EditDistList.EditDistRequest other) {
        if (other == pythonService.EditDistList.EditDistRequest.getDefaultInstance()) return this;
        if (!other.query_.isEmpty()) {
          if (query_.isEmpty()) {
            query_ = other.query_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureQueryIsMutable();
            query_.addAll(other.query_);
          }
          onChanged();
        }
        if (!other.getTarget().isEmpty()) {
          target_ = other.target_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pythonService.EditDistList.EditDistRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pythonService.EditDistList.EditDistRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList query_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureQueryIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          query_ = new com.google.protobuf.LazyStringArrayList(query_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string query = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getQueryList() {
        return query_.getUnmodifiableView();
      }
      /**
       * <code>repeated string query = 1;</code>
       */
      public int getQueryCount() {
        return query_.size();
      }
      /**
       * <code>repeated string query = 1;</code>
       */
      public java.lang.String getQuery(int index) {
        return query_.get(index);
      }
      /**
       * <code>repeated string query = 1;</code>
       */
      public com.google.protobuf.ByteString
          getQueryBytes(int index) {
        return query_.getByteString(index);
      }
      /**
       * <code>repeated string query = 1;</code>
       */
      public Builder setQuery(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureQueryIsMutable();
        query_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string query = 1;</code>
       */
      public Builder addQuery(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureQueryIsMutable();
        query_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string query = 1;</code>
       */
      public Builder addAllQuery(
          java.lang.Iterable<java.lang.String> values) {
        ensureQueryIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, query_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string query = 1;</code>
       */
      public Builder clearQuery() {
        query_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string query = 1;</code>
       */
      public Builder addQueryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureQueryIsMutable();
        query_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object target_ = "";
      /**
       * <code>string target = 2;</code>
       */
      public java.lang.String getTarget() {
        java.lang.Object ref = target_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          target_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string target = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTargetBytes() {
        java.lang.Object ref = target_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          target_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string target = 2;</code>
       */
      public Builder setTarget(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        target_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string target = 2;</code>
       */
      public Builder clearTarget() {
        
        target_ = getDefaultInstance().getTarget();
        onChanged();
        return this;
      }
      /**
       * <code>string target = 2;</code>
       */
      public Builder setTargetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        target_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pythonService.EditDistRequest)
    }

    // @@protoc_insertion_point(class_scope:pythonService.EditDistRequest)
    private static final pythonService.EditDistList.EditDistRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pythonService.EditDistList.EditDistRequest();
    }

    public static pythonService.EditDistList.EditDistRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EditDistRequest>
        PARSER = new com.google.protobuf.AbstractParser<EditDistRequest>() {
      public EditDistRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EditDistRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EditDistRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EditDistRequest> getParserForType() {
      return PARSER;
    }

    public pythonService.EditDistList.EditDistRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EditDistResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pythonService.EditDistResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated float result = 1;</code>
     */
    java.util.List<java.lang.Float> getResultList();
    /**
     * <code>repeated float result = 1;</code>
     */
    int getResultCount();
    /**
     * <code>repeated float result = 1;</code>
     */
    float getResult(int index);
  }
  /**
   * Protobuf type {@code pythonService.EditDistResponse}
   */
  public  static final class EditDistResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pythonService.EditDistResponse)
      EditDistResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EditDistResponse.newBuilder() to construct.
    private EditDistResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EditDistResponse() {
      result_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EditDistResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                result_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000001;
              }
              result_.add(input.readFloat());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                result_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                result_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          result_ = java.util.Collections.unmodifiableList(result_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pythonService.EditDistList.internal_static_pythonService_EditDistResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pythonService.EditDistList.internal_static_pythonService_EditDistResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pythonService.EditDistList.EditDistResponse.class, pythonService.EditDistList.EditDistResponse.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Float> result_;
    /**
     * <code>repeated float result = 1;</code>
     */
    public java.util.List<java.lang.Float>
        getResultList() {
      return result_;
    }
    /**
     * <code>repeated float result = 1;</code>
     */
    public int getResultCount() {
      return result_.size();
    }
    /**
     * <code>repeated float result = 1;</code>
     */
    public float getResult(int index) {
      return result_.get(index);
    }
    private int resultMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getResultList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(resultMemoizedSerializedSize);
      }
      for (int i = 0; i < result_.size(); i++) {
        output.writeFloatNoTag(result_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getResultList().size();
        size += dataSize;
        if (!getResultList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        resultMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pythonService.EditDistList.EditDistResponse)) {
        return super.equals(obj);
      }
      pythonService.EditDistList.EditDistResponse other = (pythonService.EditDistList.EditDistResponse) obj;

      boolean result = true;
      result = result && getResultList()
          .equals(other.getResultList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getResultCount() > 0) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResultList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pythonService.EditDistList.EditDistResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pythonService.EditDistList.EditDistResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pythonService.EditDistList.EditDistResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pythonService.EditDistList.EditDistResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pythonService.EditDistList.EditDistResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pythonService.EditDistList.EditDistResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pythonService.EditDistList.EditDistResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pythonService.EditDistList.EditDistResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pythonService.EditDistList.EditDistResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pythonService.EditDistList.EditDistResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pythonService.EditDistList.EditDistResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pythonService.EditDistList.EditDistResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pythonService.EditDistList.EditDistResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pythonService.EditDistResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pythonService.EditDistResponse)
        pythonService.EditDistList.EditDistResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pythonService.EditDistList.internal_static_pythonService_EditDistResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pythonService.EditDistList.internal_static_pythonService_EditDistResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pythonService.EditDistList.EditDistResponse.class, pythonService.EditDistList.EditDistResponse.Builder.class);
      }

      // Construct using pythonService.EditDistList.EditDistResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        result_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pythonService.EditDistList.internal_static_pythonService_EditDistResponse_descriptor;
      }

      public pythonService.EditDistList.EditDistResponse getDefaultInstanceForType() {
        return pythonService.EditDistList.EditDistResponse.getDefaultInstance();
      }

      public pythonService.EditDistList.EditDistResponse build() {
        pythonService.EditDistList.EditDistResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pythonService.EditDistList.EditDistResponse buildPartial() {
        pythonService.EditDistList.EditDistResponse result = new pythonService.EditDistList.EditDistResponse(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          result_ = java.util.Collections.unmodifiableList(result_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.result_ = result_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pythonService.EditDistList.EditDistResponse) {
          return mergeFrom((pythonService.EditDistList.EditDistResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pythonService.EditDistList.EditDistResponse other) {
        if (other == pythonService.EditDistList.EditDistResponse.getDefaultInstance()) return this;
        if (!other.result_.isEmpty()) {
          if (result_.isEmpty()) {
            result_ = other.result_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureResultIsMutable();
            result_.addAll(other.result_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pythonService.EditDistList.EditDistResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pythonService.EditDistList.EditDistResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Float> result_ = java.util.Collections.emptyList();
      private void ensureResultIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          result_ = new java.util.ArrayList<java.lang.Float>(result_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated float result = 1;</code>
       */
      public java.util.List<java.lang.Float>
          getResultList() {
        return java.util.Collections.unmodifiableList(result_);
      }
      /**
       * <code>repeated float result = 1;</code>
       */
      public int getResultCount() {
        return result_.size();
      }
      /**
       * <code>repeated float result = 1;</code>
       */
      public float getResult(int index) {
        return result_.get(index);
      }
      /**
       * <code>repeated float result = 1;</code>
       */
      public Builder setResult(
          int index, float value) {
        ensureResultIsMutable();
        result_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float result = 1;</code>
       */
      public Builder addResult(float value) {
        ensureResultIsMutable();
        result_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float result = 1;</code>
       */
      public Builder addAllResult(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureResultIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, result_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float result = 1;</code>
       */
      public Builder clearResult() {
        result_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pythonService.EditDistResponse)
    }

    // @@protoc_insertion_point(class_scope:pythonService.EditDistResponse)
    private static final pythonService.EditDistList.EditDistResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pythonService.EditDistList.EditDistResponse();
    }

    public static pythonService.EditDistList.EditDistResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EditDistResponse>
        PARSER = new com.google.protobuf.AbstractParser<EditDistResponse>() {
      public EditDistResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EditDistResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EditDistResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EditDistResponse> getParserForType() {
      return PARSER;
    }

    public pythonService.EditDistList.EditDistResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pythonService_EditDistRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pythonService_EditDistRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pythonService_EditDistResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pythonService_EditDistResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022EditDistList.proto\022\rpythonService\"0\n\017E" +
      "ditDistRequest\022\r\n\005query\030\001 \003(\t\022\016\n\006target\030" +
      "\002 \001(\t\"\"\n\020EditDistResponse\022\016\n\006result\030\001 \003(" +
      "\0022d\n\023EditDistServiceList\022M\n\010EditDist\022\036.p" +
      "ythonService.EditDistRequest\032\037.pythonSer" +
      "vice.EditDistResponse\"\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pythonService_EditDistRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pythonService_EditDistRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pythonService_EditDistRequest_descriptor,
        new java.lang.String[] { "Query", "Target", });
    internal_static_pythonService_EditDistResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pythonService_EditDistResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pythonService_EditDistResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
